//
// Asset loader
//

var Loader = {
    images: {}
};

var map = {
    cols: 70,
    rows: 45,
    tsize: 512,
    csize: 256,
    csize_noscr: 100,
    layers: [[
        //1              2                3                 4                5                 6                 7                 8                9                 10                11               12               13               14               15               16                17               18                 19               20               21               22                 23               24                 25                 26                 27                 28                 29                 30			        31		           32				  33                 34                 35                 36                 37                 38                 39                40                41                     42                 43                 44                 45                46                  47               48               49               50    			  51              52              53              54              55		       56		        57			    58			     59			     60			 	  61			  62			   63			      64			    65                 66               67              68              69             70
        '0map',          '0map',          '0map',           '0map',          '0map',           '0map',           '0map',           '0map',          '0map',           '0map',           '0map',          '0map',          '0map',          '0map',          '0map',          '0map',           '0map',          '0map',            '0map',          '0map',          '0map',          '0map',            '0map',          '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',           '0map',           '0map',                '0map',            '0map',            '0map',            '0map',           '0map',             '0map',          '0map',          '0map',          '0map',		  '0map',         '0map',         '0map',         '0map',         '0map',		   '0map',          '0map',         '0map',          '0map',         '0map',		  '0map',         '0map',          '0map',            '0map',           '0map',		       '0map',          '0map',         '0map',         '0map',        '0map',        
		'0map',          '0map',          '0map',           '0map',          '0map',           '0map',           '0map',           '0map',          '0map',           '0map',           '0map',          '0map',          '0map',          '0map',          '0map',          '0map',           '0map',          '0map',            '0map',          '0map',          '0map',          '0map',            '0map',          '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',           '0map',           '0map',                '0map',            '0map',            '0map',            '0map',           '0map',             '0map',          '0map',          '0map',          '0map',		  '0map',         '0map',         '0map',         '0map',         '0map',		   '0map',          '0map',         '0map',          '0map',         '0map',		  '0map',         '0map',          '0map',            '0map',           '0map',		       '0map',          '0map',         '0map',         '0map',        '0map',
		'0map',          '0map',          '0map',           '0map',          '0map',           '0map',           '0map',           '0map',          '0map',           '0map',           '0map',          '0map',          '0map',          '0map',          '0map',          '0map',           '0map',          '0map',            '0map',          '0map',          '0map',          '0map',            '0map',          '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',           '0map',           '0map',                '0map',            '0map',            '0map',            '0map',           '0map',             '0map',          '0map',          '0map',          '0map',		  '0map',         '0map',         '0map',         '0map',         '0map',		   '0map',          '0map',         '0map',          '0map',         '0map',		  '0map',         '0map',          '0map',            '0map',           '0map',		       '0map',          '0map',         '0map',         '0map',        '0map',
		'0map',          '0map',          '0map',           '0map',          '0map',           '0map',           '0map',           '0map',          '0map',           '0map',           '0map',          '0map',          '0map',          '0map',          '0map',          '0map',           '0map',          '0map',            '0map',          '0map',          '0map',          '0map',            '0map',          '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',           '0map',           '0map',                '0map',            '0map',            '0map',            '0map',           '0map',             '0map',          '0map',          '0map',          '0map',		  '0map',         '0map',         '0map',         '0map',         '0map',		   '0map',          '0map',         '0map',          '0map',         '0map',		  '0map',         '0map',          '0map',            '0map',           '0map',		       '0map',          '0map',         '0map',         '0map',        '0map',
		'0map',          '0map',          '0map',           '0map',          '0map',           '0map',           '0map',           '0map',          '0map',           '0map',           '0map',          '0map',          '0map',          '0map',          '0map',          '0map',           '0map',          '0map',            '0map',          '0map',          '0map',          '0map',            '0map',          '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',           '0map',           '0map',                '0map',            '0map',            '0map',            '0map',           '0map',             '0map',          '0map',          '0map',          '0map',		  '0map',         '0map',         '0map',         '0map',         '0map',		   '0map',          '0map',         '0map',          '0map',         '0map',		  '0map',         '0map',          '0map',            '0map',           '0map',		       '0map',          '0map',         '0map',         '0map',        '0map',
		'0map',          '0map',          '0map',           '0map',          '0map',           '0map',           '0map',           '0map',          't_tordak_w',     't_tordak',       't_acoval',      't_horn3',       't_horn2',       '0map',          '0map',          '0map',           '0map',          '0map',            '0map',          '0map',          '0map',          '0map',            '0map',          '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',           '0grs',           '0grs',                '0grs',            '0grs',            '0mnt',            '0mnt',           '0mnt',             '0mnt',          '0mnt',          '0mnt',          '0map',		  '0map',         '0map',         '0map',         '0map',         '0map', 		   '0map',          '0map',         '0map',          '0map',         '0map',		  '0map',         '0map',          '0map',            '0map',           '0map',		       '0map',          '0map',         '0map',         '0map',        '0map',
        '0map',          '0map',          '0map',           '0map',          '0map',           't_velen_ne',     't_asavir_e1',    't_asavir_e2',   't_tordak_sw',    't_tordak_s',     't_nacnar_nw',   't_nacnar_n',    't_nacnar_ne',   't_buchem_n',    '0map',          '0map',           '0map',          '0map',            '0map',          '0map',          'm_murann_n',    '0map',            'm_alibakkar_n', 'a_trademeet_nw',  'a_trademeet_n',   'a_trademeet_ne',  '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',           '0grs',           '0grs',                '0grs',            '0grs',            '0mnt',            '0mnt',           '0mnt',             '0mnt',          '0mnt',          '0mnt',          '0map',		  '0map',         '0map',         '0map',         '0map',         '0map', 		   '0map',          't_sunrise_nw', 't_sunrise_n',   't_sunrise_ne', '0map',		  '0map',         '0map',          '0map',            '0map',           '0map',		       '0map',          '0map',         '0map',         '0map',        '0map',
        '0map',          '0map',          '0map',           't_velen_w',     't_velen',        't_velen_e',      't_velenwud_nw',  't_velenwud_ne', 't_stoneblade_nw','t_stoneblade_ne','t_nacnar_w',    't_nacnarldar',  't_nacnar_e',    't_buchem',      '0map',          '0map',           't_copperclk_ne','t_honor_w',       't_honorgard',   'm_murann_sw',   'm_murann_s',    'm_tethiroad1',    'm_alibakkar',   'a_tethiroadw',    'a_trademeet',     'a_tzrd_tm1',      'a_tzrd_tm2',      'a_tzrd_tm3',      'a_tzrd_tm4',      'a_tzrd_tm5',      'a_tzrd_tzw1',     '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            'a_skullgnash_nw', 'a_skullgnash_n', 'a_skullgnash_ne','0mnt',                '0mnt',            '0mnt',            '0mnt',            '0mnt',           '0mnt',             '0mnt',          '0mnt',          '0mnt',          '0map',		  '0map',         '0map',         '0map',         '0map',         't_asharfall_nw','t_asharfall_n', 't_sunrise_w',  't_sunrise',     't_sunrise_e',  '0map',		  '0map',         '0map',          '0map',            '0map',           '0map',		       '0map',          '0map',         '0map',         '0map',        '0map',
        '0map',          '0map',          't_blackthorn_w', 't_blackthorn',  't_velmene1',     't_velmene2',     't_velenwud_w',   't_velenwud_e',  't_stoneblade_sw','t_stoneblade_se','t_nacnar_sw',   't_nacnar_s',    't_nacnar_se',   't_buchem_s',    't_copperclk_w', 't_copperclk',    't_copperclk_e', 't_honor_sw',      't_khalid1',     'm_murann_ssw',  'm_murann_ss',   'm_murann_sse',    'm_alibakkar_s', 'a_trademeet_sw',  'a_tradetrways',   'a_trademeet_se',  't_pixies_n',      't_pixies_ne',     't_cairnwheel_nw', 't_cairnwheel_n',  'a_tzrd_tzw2',     'a_tzrd_tzw3',     '0map',            '0map',            '0map',            '0map',            '0map',            'a_skullgnash_w',  'a_skullgnash',   'a_skullgnash_e', '0mnt',                '0mnt',            '0mnt',            '0mnt',            't_trstone_nw',   't_trstone_n',      't_trstone_ne',  '0map',          '0map',          '0map',		  '0map',         '0map',         '0map',         '0map',         't_asharfall_w', 't_asharfall',   't_asharfall_e','t_sunrise_s',   't_orgoth_n',   't_orgoth_ne',	  '0map',         '0map',          '0map',            '0map',           '0map',		       '0map',          '0map',         '0map',         '0map',        '0map',
        '0map',          't_bansheep_n',  't_blackthorn_sw','t_blackthorn_s','t_blackthorn_se','t_velmene3',     't_velmene4',     't_velenwud_se', 't_mongul_nw',    't_mongul_n',    't_mongul_ne',    't_drnekwud_w',  't_drnekwud',    't_drnekwud_e',  't_copperclk_sw','t_copperclk_s',  't_copperclk_se','t_fyraven_wud_ne','t_khalid2',     't_toaketh_n',   't_viperstone_n','t_rokwud_nw',     't_rokwud_n',    't_rokwud_ne',     't_trwaymos5',     't_pixies_w',      't_pixiesglenn',   't_pixies_e',      't_cairnwheel_w',  't_cairnwheel',    't_cairnwheel_e',  't_tzrd_br1',      't_tzrd_br2',      't_tzrd_br3',      '0map',            '0map',            '0map',            'a_skullgnash_sw', 'a_skullgnash_s', 'a_skullgnash_se','0map',                't_tzrd_gnt4',     't_tzrd_gnt5',     't_tzrd_gnt6',     't_trstone_w',    't_trstone',        't_trstone_e',   't_tzrd_trsto1', '0map',          '0map',		  '0map',         '0map',         't_riatavin_nw','t_riatavin_n', 't_riatavin_ne', 't_asharfall_s', 't_giantring_n','t_giantring_ne','t_orgoth',     't_orgoth_e',	  '0map',         '0map',          '0map',            '0map',           '0map',		       '0map',          '0map',         '0map',         '0map',        '0map',
        '0map',          't_bansheep',    't_bansheep_e',   't_tharamon_nw', 't_tharamon_n',   't_dragonsdown_n','t_velmene5',     't_velmene6',    't_mongul_w',     't_mongul',      't_mongul_e',     't_firerd1',     't_firerd2',     't_firerd3',     't_firerd4',     't_fyraven_wud_w','t_fyraven_wud', 't_fyraven_wud_e', 't_khalid3',     't_toaketh',     't_viperstone',  't_rokorch',       't_rokwud',      't_rokwud_e',      't_trwaymos4',     't_pixies_sw',     't_pixies_s',      't_pixies_se',     't_cairnwheel_sw', 't_cairnwheel_s',  't_brost_nw',      't_brost_n',       't_brost_ne',      't_tzrd_br4',      '0map',            '0map',            't_tzrd_tzw4',     't_tzrd_tzw5',     't_tzrd_tzw6',    't_tzrd_gnt1',    't_tzrd_gnt2',         't_tzrd_gnt3',     '0map',            't_spulzeer_nw',   't_spulzeer_n',   't_trstone_s',      't_turntower',   't_tzrd_trsto2', 't_tzrd_trsto3', 't_tzrd_trsto4', 't_tzrd_riat1', 't_tzrd_riat2', 't_riatavin_w', 't_riatavin',   't_riatavin_e',  't_giantring_w', 't_giantring',  't_giantring_e', 't_orgoth_s',   't_orgoth_se',	  '0map',         '0map',          '0map',            '0map',           '0map',		       '0map',          '0map',         '0map',         '0map',        '0map',
        '0map',          't_bansheep_s',  't_atheon_n',     't_tharamon_w',  't_tharamon',     't_dragonsdown',  't_dragonsdown_e','t_tulmene_nw',  't_tulmene_n',    '0map',          '0map',           't_firebay1',    't_firebay2',    't_firebay3',    't_firerd5',     't_firerd6',      't_firerd7',     't_firerd8',       't_jhaan',       '0map',          '0map',          't_blktomb',       't_blktomb_e',   't_rokwud_se',     't_trwaymos3',     't_brostrail6',    't_brostrail5',    't_brostrail4',    't_brostrail3',    't_brostrail2',    't_brostrail1',    't_brost',         't_brost_e',       't_tzrd_br5',      't_tzrd_tzw1',     't_tzrd_tzw2',     't_tzrd_tzw3',     't_skullgnash_w',  't_skullgnash',   't_skullgnash_e', 't_eldgate_ne',        't_eldgate_n',     't_eldgate_ne',    't_spulzeer_w',    't_spulzeer',     't_spul_road',      't_shilda_n',    't_shilda_ne',   't_hltrail1',    't_tannit_wudw', 't_tannit_wude','t_tannit_n',   't_riatavin_sw','t_riatavin_s', 't_riatavin_se', 't_rhianna_ne',  't_giantring_s','t_giantring_se','0map',         't_shining2',	  't_shining1',   '0map',          '0map',            '0map',           '0map',		       '0map',          '0map',         '0map',         '0map',        '0map',
        '0map',          '0map',          't_atheon',       't_presmer',     '0map',           't_carlsmere_n',  't_carlsmere_nw', 't_tulmene_w',   't_tulmene',      '0map',          '0map',           '0map',          '0map',          '0map',          '0map',          '0map',           '0map',          '0map',            '0map',          '0map',          '0map',          't_stdomin',       't_stdomin_e',   't_mosstone_n',    't_trwaymos2',     't_oldoakdel_n',   't_oldoakdel_ne',  't_mythrhynn_nw',  't_mythrhynn_n',   't_mythrhynn_ne',  't_brost_sw',      't_brost_s',       't_brost_se',      't_brost_hl_w',    't_brost_hl_e',    't_garlok_nw',     't_garlok_n',      't_garlok_ne',     't_nebupool_nw',  't_nebupool_n',   't_nebupool_ne',       't_eldgate',       't_eldgate_e',     't_suldell',       't_spulzeer_s',   't_shilda_w',       't_shildamere',  't_shilda_e',    't_toralth_n',   't_toralth_ne',  't_tannit_w',   't_tannithall', 't_tannit_e',   't_fldwlk_n4',  't_rhianna',	   't_rhianna_e',   '0map',         '0map',          '0map',         't_shining3',	  '0map',         '0map',          '0map',            '0map',           '0map',		       '0map',          '0map',         '0map',         '0map',        '0map',
        '0map',          '0map',          't_dargree',      't_dargree_e',   '0map',           't_carlsmere',    't_carlsmere_e',  't_firebayw1',   '0map',           '0map',          '0map',           '0map',          '0map',          '0map',          '0map',          '0map',           '0map',          '0map',            '0map',          '0map',          '0map',          't_fdrakerd2',     't_fdrakerd1',   't_mosstone',      't_trwaymos1',     't_oldoakdel',     't_talltrees_n',   't_mythrhynn_w',   't_mythrhynn',     't_mythrhynn_e',   't_kingtree_nw',   't_kingtree_n',    't_kingtree_ne',   't_linus_nw',      't_linus_n',       't_garlok_w',      't_garlok',        't_garlok_e',      't_suldaness_nw', 't_nebupool',     't_calathal_1',        't_8tree_n',       't_8tree_ne',      't_redknight_w',   't_redknight',    't_silvyr_n',       't_shilda_s',    't_toralth_wun', 't_toralth',     't_toralth_e',	  't_tannit_sw',  't_tannit_s',   't_tannitton',  't_tannitton_e','t_rhiana_s',    't_rhianna_se',  't_tzrd_elben1','t_elbencort_nw','t_elbencort_n','t_elbencort_ne','0map',         '0map',          '0map',            '0map',           '0map',		       '0map',          '0map',         '0map',         '0map',        '0map',
        '0map',          '0map',          '0map',           '0map',          '0map',           't_carlsmere_s',  't_carlsmere_se', 't_firebayw2',   '0map',           '0map',          '0map',           '0map',          '0map',          '0map',          '0map',          '0map',           '0map',          '0map',            '0map',          't_portkirn',    't_trwaykir2',   't_kirgard',       't_trwaykir3',   't_trwaykir4',     't_archdrugro',    't_oldoakdel_s',   't_talltrees',     't_mythrhynn_sw',  't_mythrhynn_s',   't_mythrhynn_se',  't_kingtree_w',    't_kingtree',      't_kingtree_e',    't_linus_w',       't_linuss',        't_linus_e',       't_garlok_s',      't_suldaness_ww',  't_suldaness_w',  't_suldaness',    't_calathal_2',        't_8tree',         't_8tree_e',       't_redknight_sw',  't_silvyr_w',     't_silvyr',         't_silvyr_e',    't_toralth_wus', 't_toralth_s',   't_toralth_se',  't_spellwud_n', 't_shelshyr_nw','t_shelshyr_n', 't_caerdusk_n', 't_fldwlk_n3',   't_yilloan_n',   't_tzrd_elben2','t_elbencort_w', 't_elbencort',  't_elbencort_e', '0map',         '0map',          '0map',            '0map',           '0map',		       '0map',          '0map',         '0map',         '0map',        '0map',
        '0map',          '0map',          '0map',           '0map',          '0map',           '0map',           '0map',           '0map',          '0map',           '0map',          '0map',           '0map',          't_stspmntn1',   't_stspmntn2',   't_adlir',       't_stspmntn3',    't_stspmntn4',   't_stspmntn5',     't_stspmntn6',   't_portkir',     't_trwaykir1',   't_tresqylr1',     't_tresqylr2',   't_tresqyl',       't_tresqyl_e',     't_cayrthal_n',    't_talltrees_s',   't_kalmin_n',      't_hunttree_w',    't_hunttree',      't_hunttree_e',    't_morndiv_up',    't_kingtree_se',   't_linus_sw',      't_linus_s',       't_linus_se',      't_panse_nw',      't_panse_n',       't_suldaness_sw', 't_suldaness_s',  't_calathal_3',        't_8tree_s',       't_8tree_se',      't_zoastriast',    't_silvyr_sw',    't_silvyr_s',       't_9star_n',     't_innocence',   't_hltrail2',    't_hltrail3',	  't_spellwud',   't_shelshyr_w', 't_shelshyr',   't_caerdusk',   't_fldwlk_n2',   't_yilloan_s',   't_nomer_nw',   't_nomer_n',     't_elbencort_s','0map',		  '0map',         '0map',          '0map',            '0map',           '0map',		       '0map',          '0map',         '0map',         '0map',        '0map',
        '0map',          '0map',          '0map',           '0map',          '0map',           '0map',           '0map',           '0map',          '0map',           '0map',          '0map',           '0map',          't_stspmnts1',   't_stspmnts2',   't_stspmnts3',   't_stspmnts4',    't_ramedar',     't_bormuln5',      '0mnt',          '0mnt',          't_trwayzaz3',   '0mnt',            't_grimjaws',    '0mnt',            't_cayrthal_w',    't_cayrthal',      't_cayrthal_e',    't_kalmin',        't_kalmin_e',      't_hawkrook4',     't_hawkrook5',     '0mnt',            't_argent_nw',     't_argent_n',      't_dunod_nw',      't_dunod_n',       't_stpiretr14',    't_panse',         't_stpiretr13',   't_stpiretr12',   't_calathal_4',        't_calathal_5',    't_calathal_6',    't_moongld',       't_moongld_e',    't_9star_w',        't_9star',       't_hartwud',     't_nanarch',     't_hltrail4',	  't_spellwud_s', 't_shelshyr_sw','t_shelshyr_s', 't_caerdusk_s', 't_fldwlk_n1',   't_morning_nw',  't_morning_n',  't_nomer',       't_nomer_e',    '0map',		  '0map',         '0map',          '0map',            '0map',           '0map',		       '0map',          '0map',         '0map',         '0map',        '0map',
        '0map',          '0map',          '0map',           '0map',          '0map',           '0map',           '0map',           '0map',          '0map',           '0map',          '0map',           '0map',          '0map',          '0map',          '0map',          '0map',           't_bormuln4',    't_bormuln3',      't_battlesend',  '0mnt',          't_trwayzaz2',   '0mnt',            '0mnt',          '0mnt',            '0mnt',            't_memory',        't_samyte_to',     't_strohm_to',     't_uluran_n',      't_tresper',       '0mnt',            '0mnt',            't_argent_w',      't_argentwing',    't_dunod_w',       't_dunod',         't_stpiretr15',    't_panse_s',       't_targyll',      't_stpiretr11',   't_tweyar_n',          't_tweyar_ne',     't_moongld_sw',    't_moongld_s',     't_moongld_se',   't_sulduskoonar',   't_sulduskoo_e', 't_hartshall',   't_hltrail6',    't_hltrail5',	  '0map',         '0map',         '0map',         '0map',         't_st_alaric_n', 't_morning_w',   't_morning',    't_morning_e',   't_nomer_se',   '0map',		  '0map',         't_swimstar9',   '0map',            '0map',           '0map',		       '0map',          '0map',         '0map',         '0map',        '0map',
        '0map',          '0map',          '0map',           '0map',          '0map',           '0map',           '0map',           '0map',          '0map',           '0map',          '0map',           '0map',          '0map',          '0map',          '0map',          '0map',           '0map',          '0map',            't_bormuln2',    't_bormuln1',    't_trwayzaz1',   't_tinker_w',      't_tinker',      't_9ladies_nw',    't_9ladies_n',     't_memory_s',      't_samyte_tos',    't_uluran_w',      't_uluran',        't_hawkrook3',     't_stpiretr1',     't_banshi_n',      't_banshi_ne',     't_argent_s',      't_dunod_sw',      't_dunod_s',       't_dunod_se',      't_stpiretr8',     't_stpiretr9',    't_stpiretr10',   't_tweyar',            't_varyth_torf_w', 't_varyth_tor',    't_varyth_torf_e', 't_sulduskoo_sw', 't_sulduskoo_s',    't_sulduskoo_se','t_hartshall_s', 't_hltrail7',    '0map',		  '0map',         '0map',         '0map',         't_iltkazar_n', 't_st_alaric',   't_st_alaric_e', 't_morning_s',  't_morning_se',  't_rivertrk1',  '0map',		  't_swimstar7',  't_swimstar8',   '0map',            't_rrinno',       '0map',		       'e_turbold',     '0map',         '0map',         '0map',        '0map',
        '0map',          '0map',          '0map',           '0map',          '0map',           '0map',           '0map',           '0map',          '0map',           '0map',          '0map',           '0map',          '0map',          '0map',          '0map',          '0map',           '0map',          '0map',            '0map',          't_zazesspur_nw','t_zazesspur_ne','t_tinker_sw',     't_tinker_s',    't_9ladies_w',     't_9ladies',       't_9ladies_e',     't_9ladies_ee',    't_uluran_sw',     't_hawkrook2',     't_uluran_se',     't_stpiretr2',     't_banshi',        't_stpiretr3',     't_stpiretr4',     't_stpiretr5',     't_stpiretr6',     't_stpiretr7',     't_lhestyn_quay',  't_masamont_road','t_masamount',    't_masamount_wudn',    't_varyth_torf_sw','t_varyth_torf_s', 't_varyth_torf_se','t_varyth_wud_w', 't_varyth_wud',     't_varyth_wud_e','t_hartshall_ss','t_hltrail8',    '0map',		  '0map',         '0map',         '0map',         't_iltkazar',   't_st_alaric_s', 't_st_alaric_se','t_swimstar3',  't_swimstar4',   't_rivertrk2',  't_swimstar5',	  't_swimstar6',  '0map',          '0map',            '0map',           't_kartak',        '0map',          '0map',         '0map',         '0map',        '0map',
        '0map',          '0map',          '0map',           '0map',          '0map',           '0map',           '0map',           '0map',          '0map',           '0map',          '0map',           '0map',          '0map',          '0map',          '0map',          '0map',           '0map',          '0map',            '0map',          't_zazesspur_sw','t_zazesspur_se','t_venezir_ne'  ,  't_marakir',     't_9ladies_sw',    't_9ladies_s',     't_tethyrcast_nw', 't_tethyrcast_n',  't_tethyrcast_ne', 't_hawkrook1',     't_uluran_ses',    't_banshi_sw',     't_hostim_quay',   't_ithmn_sul_e',   't_ithmn_sul_e1',  't_ithmn_sul_e2',  't_grannox',       't_grannox_farms', 't_lhestynheart',  't_freelm_farms', 't_freelmanse',   't_masamount_wuds',    't_varyth_plain_w','t_varyth_plain_c','t_varyth_plain_e','t_iltarghal_nww','t_iltarghal_nw',   't_iltarghal_n', 't_iltarghal_ne','t_hltrail9',    't_survale_ne',  '0map',         '0map',         '0map',         't_iltkazar_s', 't_fldwlk_s1',   't_swimstar1',   't_swimstar2',  '0map',          't_lyllburg_n', 't_lyllburg_ne', '0map',         '0map',          '0map',            '0map',           '0map',            'e_tibold',      '0map',         '0map',         '0map',        '0map',
        '0map',          '0map',          '0map',           '0map',          '0map',           '0map',           '0map',           '0map',          '0map',           '0map',          '0map',           '0map',          '0map',          '0map',          '0map',          '0map',           '0map',          '0map',            '0map',          't_venezir_sw',  't_venezir_s',   't_venezir_se'  ,  't_marakir_s1',  't_marakir_s2',    't_marakir_s3',    't_tethyrcast_w',  't_tethyrcast',    't_tethyrcast_e',  't_alemwood_nw',   't_alemwood_ne',   't_hostim_hill_nw','t_hostim',        't_hostim_wood',   't_ithmon_crag_nw','t_ithmon_crag_ne','t_lhest_gorge',   't_lhest_farm_sw', 't_lhest_farm_s',  't_lhest_farm_se','t_rivshrehill_n','t_rivshrehill_ne',    't_varyth_hill_nw','t_varyth_hill_n', 't_varyth_hill_ne','t_iltarghal_ww', 't_iltarghal_w',    't_iltarghal',   't_survale_w',   't_survale',     't_survale_e',   't_survale_ee', 't_gorge1',     't_gorge2',     't_gorge3',     't_fldwlk_s2',   '0map',          '0map',         '0map',          't_lyllburg',   't_lyllburg_e',  '0map',         '0map',          '0map',            '0map',           '0map',	           '0map',          'e_golconda',   '0map',         '0map',        '0map',
        '0map',          '0map',          '0map',           '0map',          '0map',           '0map',           '0map',           '0map',          '0map',           '0map',          '0map',           '0map',          '0map',          '0map',          '0map',          '0map',           '0map',          '0map',            't_faithful',    't_hilltr1',     't_hilltr2',     't_vintor_okr_1',  't_vintor_okr_2','t_vintor_okr_3',  't_bardshyr_okr',  't_tethyrcast_sw', 't_tethyrcast_s',  't_tethyrcast_se', 't_alemwood_sw',   't_bardshyr_alem', 't_hostim_hill_w', 't_hostim_road',   't_hostim_hill_e', 't_ithmon_crag_sw','t_ithmon_crag_se','t_qonsir',        't_qonsir_farm',   't_lhest_road',    't_rivshrehill_w','t_rivshrehill_c','t_st_ostus',          't_varyth_hill_sw','t_varyth_hill_s', 't_varyth_hill_se','t_iltarghal_wws','t_iltarghal_sw',   't_iltarghal_s', 't_survale_sw',  't_survale_s',   't_survale_se',  '0map',         '0map',         '0map',         't_idolflow1',  't_fldwlk_s3',   '0map',          '0map',         '0map',          't_noble_nw',   't_noble_n',	  't_noble_ne',   '0map',          '0map',            '0map',           '0map',		       'e_ravimor',     '0map',         '0map',         '0map',        '0map',
        '0map',          '0map',          '0map',           '0map',          '0map',           '0map',           '0map',           '0map',          '0map',           '0map',          '0map',           '0map',          '0map',          '0map',          '0map',          '0map',           '0map',          '0map',            't_bormuls',     't_purhilla1',   't_canaith',     't_purhillb1',     't_purhillc1',   't_purhilld1',     't_sahark_crossrd','t_saharkhan',     't_bardshy_itr_1', 't_bardshy_itr_2', 't_bardshy_itr_3', 't_bardshy_itr_4', 't_ithmon_ithr_w1','t_ithmon_ithr_w2','t_ithmon_lorcros','t_ithmon_ithr_e1','t_ithmon_ithr_e2','t_rvrshr_ithrdw', 't_crownfarms_nw', 't_crownfarms_n',  't_crownfarms_ne','t_rivshrehill_s','t_rivshrehill_se',    't_thrynnar_ww',   't_thrynnar_w',    't_thrynnar_hold', 't_thynnar_e',    't_survale_rd1',    't_survale_rd2', 't_survale_rd3', 't_survale_rd4', 't_veadd_n',     't_veadd_ne',   '0map',         '0map',         '0map',         't_fldwlk_s4',   't_idolflow2',   't_levast1',    't_levast2',     't_noble_w',    't_noble',	 	  't_noble_e',    '0map',          '0map',            '0map',           'e_starrock_w',    'e_starrock',    'e_starrock_e', '0map',         '0map',        '0map',
        '0map',          '0map',          '0map',           '0map',          '0map',           '0map',           '0map',           '0map',          '0map',           '0map',          '0map',           '0map',          '0map',          '0map',          '0map',          '0map',           '0map',          '0map',            't_ithalyr',     't_purhilla2',   't_hilltr3',     't_purhillb2',     't_purhillc2',   't_purhilld2',     't_soldieroad_1',  't_saharkhan_sp',  't_sevenstar_rd',  't_sevenstar_hne', 't_brinniqdell_n', 't_brinniqwood_n', 't_ithmon_pipe_n', 't_ithmon_farm_nw','t_ithmon_farm_n', 't_ithmon_farm_ne','t_loransewood_n', 't_crownfarms_iw2','t_crownfarms_iw1','t_darromar',      't_foyen_rd',     't_foyen',        '0map',                't_thrynnar_sww',  't_thrynnar_sw',   't_thynnar_s',     't_clovis_nw',    't_clovis_n',       't_clovis_ne',   '0map',          't_veadd_w',     't_veaddakar',   't_veadd_e',    '0map',         '0map',         '0map',         't_fldwlk_s5',   't_idolflow3',   '0map',         '0map',          't_noble_sw',   't_noble_s',	  't_noble_se',   '0map',          '0map',            '0map',           'e_starrock_sw',   'e_starrock_s',  'e_starrock_se','0map',         '0map',        '0map',
        '0map',          '0map',          '0map',           '0map',          '0map',           '0map',           '0map',           '0map',          '0map',           '0map',          '0map',           '0map',          '0map',          '0map',          '0map',          '0map',           '0map',          '0map',            't_purclif5',    't_purhilla3',   't_barrows',     't_samytew',       't_dasaajk',     't_samytee',       't_soldieroad_2',  't_jongrathroad11','t_sevenstar',     't_sevenstar_hse', 't_brinniqdell_s', 't_brinniqwood',   't_ithmon_pipe_s', 't_ithmon_farm_w', 't_ithmon_loranse','t_ithmon_farm_e', 't_loransewood_s', 't_abbor_n',       't_darromar_sw',   't_darromar_s',    't_darromar_se',  '0map',           '0map',                't_clovis_rd1',    't_clovis_rd2',    't_clovis_rd3',    't_clovis_w',     't_clovis',         't_clovis_e',    '0map',          't_veadd_sw',    't_veadd_s',	  't_veadd_se',   't_ithlink1',   '0map',         '0map',         't_fldwlk_s6',   't_idolflow4',   't_spires_n',   't_spires_ne',   't_levast3',    '0map',		  '0map',         '0map',          '0map',            '0map',           '0map',		       '0map',          '0map',         '0map',         '0map',        '0map',
        '0map',          '0map',          '0map',           '0map',          '0map',           '0map',           '0map',           '0map',          '0map',           '0map',          '0map',           '0map',          '0map',          '0map',          '0map',          '0map',           '0map',          '0map',            't_rhynda',      't_rhynda_rd',   't_hilltr4',     't_purhillb3',     't_purhillc3',   't_purhilld3',     't_krennasar',     't_jongrathroad01','t_jongrathroad02','t_jongrath',      't_jongrathroad03','t_brinniqwood_s', 't_loranse_swamp', 't_st_natan_nw',   't_st_natan_n',    't_st_natan_ne',   't_abbor_w',       't_abbor',         't_abbor_e',       't_ruba_nw',       't_ruba_n',       't_ruba_ne',      't_ithrd_mis1',        't_ithrd_mis2',    '0map',            '0map',            't_clovis_sw',    't_clovis_s',       't_clovis_se',   '0map',          '0map',          '0map',		  '0map',         't_ithlink2',   't_ithlink3',   't_ithlink4',   't_fldwlk_s7',   't_upparkol_n',  't_spires',     't_spires_e',    't_levast4',    '0map',		  '0map',         '0map',          'e_praskallest_nw','e_praskallest_n','e_praskallest_ne','0map',          '0map',         '0map',         '0map',        '0map',
        '0map',          '0map',          '0map',           '0map',          '0map',           '0map',           '0map',           '0map',          '0map',           '0map',          '0map',           '0map',          '0map',          '0map',          '0map',          '0map',           '0map',          '0map',            't_purclif4',    't_purhilla4',   't_vineshade',   't_purhillb4',     't_redmills',    't_elem_solroad01','t_elem_solroa002','t_elem_farm1',    't_elem_farm2',    't_elem_farm3',    't_elem_farm4',    't_riverith7',     't_riverith8',     't_st_natan_w',    't_st_natan',      't_st_natan_e',    't_abbor_sw',      't_abbor_s',       't_abbor_se',      't_ruba_w',        't_ruba',         't_ruba_e',       't_mistle_nw',         't_mistle_n',      't_mistle_ne',     't_ithrd_mis3',    't_ithrd_mis4',   't_ithrd_barak1',   '0map',          't_barak_nw',    't_barak_n',     't_barak_ne',	  '0map',         '0map',         '0map',         't_sarad_nw',   't_sarad_n',     't_upparkol',    't_spires_s',   't_orator',      't_levast5',    't_borthund_nw', 't_borthund_n', 't_borthund_ne', 'e_praskallest_w', 'e_praskallest',  'e_praskallest_e', '0map',          '0map',         '0map',         '0map',        '0map',
        '0map',          '0map',          '0map',           '0map',          '0map',           '0map',           '0map',           '0map',          '0map',           '0map',          '0map',           '0map',          '0map',          '0map',          '0map',          '0map',           '0map',          '0map',            't_purclif3',    't_purhilla5',   't_hilltr5',     't_purhillb5',     't_refields_n',  't_refields_ne',   't_riverith1',     't_riverith2',     't_riverith3',     't_riverith4',     't_riverith5',     't_riverith6',     '0map',            't_st_natan_sw',   't_st_natan_s',    't_st_natan_se',   't_pelmarin_nw',   't_pelmarin_n',    't_pelmarin_ne',   't_ruba_sw',       't_ruba_s',       't_ruba_se',      't_mistle_w',          't_mistletoe',     't_mistle_e',      '0map',            '0map',           't_ithrd_barak2',   't_ithrd_barak3','t_barak_w',     't_barakmordin', 't_barak_e',	  't_triad_rd1',  't_triad_rd2',  't_triad_rd3',  't_sarad_w',    't_saradush',    't_sarad_e',     't_colber_n',   't_earthsky_nw', 't_earthsky_ne','t_borthund_w',  't_borthund',   't_borthund_e',  'e_praskallest_sw','e_praskallest_s','e_praskallest_se','0map',          '0map',         '0map',         '0map',        '0map',
        '0map',          '0map',          '0map',           '0map',          '0map',           '0map',           '0map',           '0map',          '0map',           '0map',          '0map',           '0map',          '0map',          '0map',          '0map',          '0map',           '0map',          '0map',            't_purclif2',    't_purclif1',    't_ith_est',     't_myratma_w',     't_myratma_e',   't_refields_e',    't_calim_rd1',     't_marat_w',       't_maratimmir',    't_marat_e',       't_calim_rd2',     't_calim_rd3',     't_calim_rd4',     't_calim_rd5',     't_calim_rd6',     't_calim_rd7',     't_pelmarin_w',    't_pelmarin',      't_pelmarin_e',    '0map',            '0map',           '0map',           't_mistle_sw',         't_mistle_s',      't_mistle_se',     '0map',            '0map',           't_magis_rd',       't_adarthir_nw', 't_adarthir_n',  't_barak_s',     't_barak_se',	  't_passride1',  '0map',         '0map',         't_sarad_sw',   't_sarad_s',     't_colber_w',    't_colbertann', 't_earthsky_sw', 't_earthsky_se','t_borthund_sw', 't_borthund_s', 't_borthund_se', '0map',            '0map',           '0map',		       '0map',          '0map',         '0map',         '0map',        '0map',
        '0map',          '0map',          '0map',           '0map',          '0map',           '0map',           '0map',           '0map',          '0map',           '0map',          '0map',           '0map',          '0map',          '0map',          '0map',          '0map',           '0map',          '0map',            '0map',          '0map',          't_trwaycal3',   't_trwaycal2',     't_trwaycal1',   't_marat_h_nw',    't_marat_h_n',     't_marat_sw',      't_marat_s',       't_marat_se',      't_teqlar_nw',     't_teqlar_n',      't_teqlar_ne',     't_monthills_w',   't_monthills',     't_monthills_e',   't_pelmarin_sw',   't_pelmarin_s',    't_pelmarin_se',   '0map',            '0map',           '0map',           '0map',                '0map',            '0map',            't_magis_nw',      't_magis_n',      't_magis_ne',       't_adarthir_w',  't_adarthir',    't_adarthir_e',  '0map',		  't_passride2',  't_passride3',  '0map',         't_dutywalk3',  't_dutywalk4',   't_colber_sw',   't_colber_s',   't_colber_se',   't_sleeping_nw','t_sleeping_n',  't_sleeping_ne','0map',          '0map',            'e_fortblood_nw',	'e_fortblood_n',   'e_fortblood_ne','0map',         '0map',         '0map',        '0map',
        '0map',          '0map',          '0map',           '0map',          '0map',           '0map',           '0map',           '0map',          '0map',           '0map',          '0map',           '0map',          '0map',          '0map',          '0map',          '0map',           '0map',          '0map',            '0map',          '0map',          't_trwaycal4',   't_daraq_hw',      't_daraq_he',    't_marat_h_w',     't_marat_h',       't_marat_h_e',     't_marat_plw',     't_marat_ple',     't_teqlar_w',      't_teqlar',        't_shoonfedw',     't_shoonach_ilt',  't_shoonach_run',  't_shoonach_deb',  't_shoon_pln',     't_qian_rd1',      't_khanall_nw',    't_khanall_n',     't_khanall_ne',   't_vorpal_nw',    't_vorpal_n',          't_vorpal_ne',     '0map',            't_magis_w',       't_magis_tor',    't_magis_e',        't_adarthir_sw', 't_adarthir_s',  't_adarthir_se', '0map',		  '0map',         't_passride4',  '0map',         't_dutywalk2',  '0map',		   '0map',          '0map',         '0map',          't_sleeping_w', 't_sleeping',    't_sleeping_e', '0map',          '0map',            'e_fortblood_w',	'e_fortblood',     'e_fortblood_e', '0map',         '0map',         '0map',        '0map',
        '0map',          '0map',          '0map',           '0map',          '0map',           '0map',           '0map',           '0map',          '0map',           '0map',          '0map',           '0map',          '0map',          '0map',          '0map',          '0map',           '0map',          '0map',            '0map',          't_daraqadim',   't_trwaycal5',   't_fortagis_nw',   't_fortagis_n',  't_fortagis_ne',   't_marat_h_s',     't_iltakar_nw',    't_iltakar_n',     't_iltakar_ne',    't_agisroad7',     't_shoonach_gaw',  't_shoonach_mum',  't_shoonach_imp',  't_shoonfede',     't_shoonach_gae',  't_shoon_pls',     't_qian_rd2',      't_khanall_w',     't_khanall',       't_khanall_e',    't_vorpal_w',     't_vorpal',            't_vorpal_e',      '0map',            't_magis_sw',      't_magis_s',      't_magis_se',       't_allsih',      't_allsih_e',    '0map',          '0map',		  '0map',         't_passride5',  't_passride6',  't_dutywalk1',  '0map',		   '0map',          '0map',         '0map',          't_sleeping_sw','t_sleeping_s',  't_sleeping_se','0map',          '0map',            'e_fortblood_sw',	'e_fortblood_s',   'e_fortblood_se','0map',         '0map',         '0map',        '0map',
        '0map',          '0map',          '0map',           '0map',          '0map',           '0map',           '0map',           '0map',          '0map',           '0map',          '0map',           '0map',          '0map',          '0map',          '0map',          '0map',           'c_memmonw',     'c_memmone',       't_memmonnar',   't_trwaycal6',   't_agisroad1',   't_agisroad2',     't_fortagis',    't_agisroad3',     't_agisroad4',     't_agisroad5',     't_iltakargarr',   't_agisroad6',     't_fortcalim',     'c_agisshoo1',     'c_agisshoo2',     't_shoonach_agi',  'c_agisshoo3',     'c_agisshoo4',     'c_agisshoo5',     't_qian_n',        't_qian_ne',       't_khanall_s',     't_khanall_se',   't_vorpal_sw',    't_vorpal_s',          't_vorpal_se',     '0map',            '0map',            '0map',           't_allsih_sw',      't_allsih_s',    't_allsih_se',   '0map',	         '0map',		  't_argentor_nw','t_argentor_n', 't_ithal_nw',   't_ithal_n',    't_ithal_ne',    '0map',          '0map',         '0map',          '0map',         '0map',		  '0map',         '0map',          '0map',            '0map',           '0map',		       '0map',          '0map',         '0map',         '0map',        '0map',
        '0map',          '0map',          '0map',           '0map',          '0map',           '0map',           '0map',           '0map',          '0map',           '0map',          '0map',           '0map',          '0map',          '0map',          '0map',          '0map',           '0map',          '0map',            '0map',          '0map',          '0map',          '0map',            '0map',          '0map',            't_fortufenk',     '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            'c_agisshoo6',     't_qian',          't_qian_e',        '0map',            't_gommat_nw',    't_gommat_n',     't_gommat_ne',         '0map',            '0map',            '0map',            't_dallnot_nw',   't_dallnot_n',      't_dallnot_ne',  '0map',          '0map',          '0map',		  't_argentor_w', 't_argentor',   't_ithal_w',    't_ithal',      't_ithal_e',     '0map',          '0map',         '0map',          '0map',         '0map',		  '0map',         '0map',          '0map',            '0map',           '0map',		       '0map',          '0map',         '0map',         '0map',        '0map',
        '0map',          '0map',          '0map',           '0map',          '0map',           '0map',           '0map',           '0map',          '0map',           '0map',          '0map',           '0map',          '0map',          '0map',          '0map',          '0map',           '0map',          '0map',            '0map',          '0map',          '0map',          '0map',            '0map',          '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            'c_ul_sahab_nw',   'c_ul_sahab_n',    't_gommat_w',     't_gommat',       't_gommat_e',          '0map',            't_iskass_nw',     't_iskass_n',      't_dallnot_w',    't_dallnot',        't_dallnot_e',   '0map',          '0map',          't_dyraalis_nw', 't_dyraalis_n', 't_dyraalis_ne','t_ithal_sw',   't_ithal_s',    't_ithal_se',    '0map',          '0map',         '0map',          '0map',         '0map',		  '0map',         '0map',          '0map',            '0map',           '0map',		       '0map',          '0map',         '0map',         '0map',        '0map',
		'0map',          '0map',          '0map',           '0map',          '0map',           '0map',           '0map',           '0map',          '0map',           '0map',          '0map',           '0map',          '0map',          '0map',          '0map',          '0map',           '0map',          '0map',            '0map',          '0map',          '0map',          '0map',            '0map',          '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            'c_abbalayat',     'c_ul_sahab',      'c_ul_sahab_e',   '0map',           '0map',                '0map',            't_iskass_w',      't_iskass',        't_iskass_e',     't_dallnot_s',      't_hollday_nw',  't_hollday_n',   't_hollday_ne',  't_dyraalis_w',  't_dyraalis',   't_dyraalis_e', '0map',         't_uller_w',    't_uller',	   't_uller_e',     '0map',         '0map',          '0map',         '0map',		  '0map',         '0map',          '0map',            '0map',           '0map',		       '0map',          '0map',         '0map',         '0map',        '0map',
		'0map',          '0map',          '0map',           '0map',          '0map',           '0map',           '0map',           '0map',          '0map',           '0map',          '0map',           '0map',          '0map',          '0map',          '0map',          '0map',           '0map',          '0map',            '0map',          '0map',          '0map',          '0map',            '0map',          '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            'c_ul_sahab_sw',   'c_ul_sahab_s',    'c_ul_sahab_se',  '0map',           '0map',                '0map',            '0map',            '0map',            '0map',           '0map',             't_hollday_w',   't_hollday',     't_hollday_e',   't_dyraalis_sw', 't_dyraalis_s', 't_dyraalis_se','0map',         't_uller_sw',   't_uller_s',	   't_kzelter_nw',  't_kzelter_n',  't_kzelter_ne',  '0map',         '0map',		  '0map',         '0map',          '0map',            '0map',           '0map',		       '0map',          '0map',         '0map',         '0map',        '0map',
		'0map',          '0map',          '0map',           '0map',          '0map',           '0map',           '0map',           '0map',          '0map',           '0map',          '0map',           '0map',          '0map',          '0map',          '0map',          '0map',           '0map',          '0map',            '0map',          '0map',          '0map',          '0map',            '0map',          '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',           '0map',           '0map',                '0map',            '0map',            '0map',            '0map',           '0map',             't_hollday_sw',  't_hollday_s',   'c_sarengard_n', 'c_sarengard_ne','c_rutawwa_nw', 'c_rutawwa_n',  'c_rutawwa_ne', '0map',         'c_mariam_rd',   't_kzelter_w',   't_kzelter',    't_kzelter_e',   '0map',         '0map',		  '0map',         '0map',          '0map',            '0map',           '0map',		       '0map',          '0map',         '0map',         '0map',        '0map',
		'0map',          '0map',          '0map',           '0map',          '0map',           '0map',           '0map',           '0map',          '0map',           '0map',          '0map',           '0map',          '0map',          '0map',          '0map',          '0map',           '0map',          '0map',            '0map',          '0map',          '0map',          '0map',            '0map',          '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',           '0map',           '0map',                '0map',            '0map',            '0map',            '0map',           '0map',             '0map',          '0map',          'c_sarengard',   'c_minthrux',    'c_rutawwa_w',  'c_rutawwa',    'c_rutawwa_e',  'c_mariam_n',   'c_mariam_ne',   't_kzelter_sw',  't_kzelter_s',  't_kzelter_se',  '0map',         '0map',		  '0map',         '0map',          '0map',            '0map',           '0map',		       '0map',          '0map',         '0map',         '0map',        '0map',
		'0map',          '0map',          '0map',           '0map',          '0map',           '0map',           '0map',           '0map',          '0map',           '0map',          '0map',           '0map',          '0map',          '0map',          '0map',          '0map',           '0map',          '0map',            '0map',          '0map',          '0map',          '0map',            '0map',          '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',           '0map',           '0map',                '0map',            '0map',            '0map',            '0map',           '0map',             '0map',          '0map',          '0map',          '0map',		  'c_rutawwa_sw', 'c_rutawwa_s',  'c_mariam_w',   'c_mariam',     'c_mariam_e',	   '0map',          '0map',         '0map',          '0map',         '0map',		  '0map',         '0map',          '0map',            '0map',           '0map',		       '0map',          '0map',         '0map',         '0map',        '0map',
		'0map',          '0map',          '0map',           '0map',          '0map',           '0map',           '0map',           '0map',          '0map',           '0map',          '0map',           '0map',          '0map',          '0map',          '0map',          '0map',           '0map',          '0map',            '0map',          '0map',          '0map',          '0map',            '0map',          '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',           '0map',           '0map',                '0map',            '0map',            '0map',            '0map',           '0map',             '0map',          '0map',          '0map',          '0map',	  	  '0map',         '0map',         'c_mariam_sw',  'c_mariam_s',   'c_mariam_se',   '0map',          '0map',         '0map',          '0map',         '0map',		  '0map',         '0map',          '0map',            '0map',           '0map',		       '0map',          '0map',         '0map',         '0map',        '0map',
		'0map',          '0map',          '0map',           '0map',          '0map',           '0map',           '0map',           '0map',          '0map',           '0map',          '0map',           '0map',          '0map',          '0map',          '0map',          '0map',           '0map',          '0map',            '0map',          '0map',          '0map',          '0map',            '0map',          '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',           '0map',           '0map',                '0map',            '0map',            '0map',            '0map',           '0map',             '0map',          '0map',          '0map',          '0map',		  '0map',         '0map',         '0map',         '0map',         '0map',		   '0map',          '0map',         '0map',          '0map',         '0map',		  '0map',         '0map',          '0map',            '0map',           '0map',		       '0map',          '0map',         '0map',         '0map',        '0map',
		'0map',          '0map',          '0map',           '0map',          '0map',           '0map',           '0map',           '0map',          '0map',           '0map',          '0map',           '0map',          '0map',          '0map',          '0map',          '0map',           '0map',          '0map',            '0map',          '0map',          '0map',          '0map',            '0map',          '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',           '0map',           '0map',                '0map',            '0map',            '0map',            '0map',           '0map',             '0map',          '0map',          '0map',          '0map',		  '0map',         '0map',         '0map',         '0map',         '0map',		   '0map',          '0map',         '0map',          '0map',         '0map',		  '0map',         '0map',          '0map',            '0map',           '0map',		       '0map',          '0map',         '0map',         '0map',        '0map',
		'0map',          '0map',          '0map',           '0map',          '0map',           '0map',           '0map',           '0map',          '0map',           '0map',          '0map',           '0map',          '0map',          '0map',          '0map',          '0map',           '0map',          '0map',            '0map',          '0map',          '0map',          '0map',            '0map',          '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',            '0map',           '0map',           '0map',                '0map',            '0map',            '0map',            '0map',           '0map',             '0map',          '0map',          '0map',          '0map',		  '0map',         '0map',         '0map',         '0map',         '0map',		   '0map',          '0map',         '0map',          '0map',         '0map',		  '0map',         '0map',          '0map',            '0map',           '0map',		       '0map',          '0map',         '0map',         '0map',        '0map'
    ],[
      //                  10                  20                  30                  40                  50				  60                  70
      //1 2 3 4 5 6 7 8 9   1 2 3 4 5 6 7 8 9   1 2 3 4 5 6 7 8 9   1 2 3 4 5 6 7 8 9   1 2 3 4 5 6 7 8 9   1 2 3 4 5 6 7 8 9   1 2 3 4 5 6 7 8 9 
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
		0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
		0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
		0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
		0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
		0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
		0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
		0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
		0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,		
		0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
		0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
		0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
		0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
		0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
    ]],
    getTile: function (layer, col, row) {
        return this.layers[layer][row * map.cols + col];
    }
}; 

Loader.loadImage = function (key, src) {
    var img = new Image();

    var d = new Promise(function (resolve, reject) {
        img.onload = function () {
            this.images[key] = img;
            resolve(img);
        }.bind(this);

        img.onerror = function () {
            reject('Could not load image: ' + src);
        };
    }.bind(this));

    img.src = src;
    return d;
};

Loader.getImage = function (key) {
    return (key in this.images) ? this.images[key] : null;
};

//
// Keyboard handler
//

var Keyboard = {};

Keyboard.LEFT = 37;
Keyboard.RIGHT = 39;
Keyboard.UP = 38;
Keyboard.DOWN = 40;

Keyboard._keys = {};

Keyboard.listenForEvents = function (keys) {
    window.addEventListener('keydown', this._onKeyDown.bind(this));
    window.addEventListener('keyup', this._onKeyUp.bind(this));

    keys.forEach(function (key) {
        this._keys[key] = false;
    }.bind(this));
}

Keyboard._onKeyDown = function (event) {
    var keyCode = event.keyCode;
    if (keyCode in this._keys) {
        event.preventDefault();
        this._keys[keyCode] = true;
    }
};

Keyboard._onKeyUp = function (event) {
    var keyCode = event.keyCode;
    if (keyCode in this._keys) {
        event.preventDefault();
        this._keys[keyCode] = false;
    }
};

Keyboard.isDown = function (keyCode) {
    if (!keyCode in this._keys) {
        throw new Error('Keycode ' + keyCode + ' is not being listened to');
    }
    return this._keys[keyCode];
};

//
// Game object
//

var Game = {};

Game.run = function (context) {
    this.ctx = context;
    this._previousElapsed = 0;

    var p = this.load();
    Promise.all(p).then(function (loaded) {
        this.init();
        window.requestAnimationFrame(this.tick);
    }.bind(this));
};

Game.tick = function (elapsed) {
    window.requestAnimationFrame(this.tick);

    // clear previous frame
    this.ctx.clearRect(0, 0, 512, 512);

    // compute delta time in seconds -- also cap it
    var delta = (elapsed - this._previousElapsed) / 1000.0;
    delta = Math.min(delta, 0.25); // maximum delta of 250 ms
    this._previousElapsed = elapsed;

    this.update(delta);
    this.render();
}.bind(Game);

// override these methods to create the demo
Game.init = function () {};
Game.update = function (delta) {};
Game.render = function () {};

//
// start up function
//

window.onload = function () {
    var context = document.getElementById('demo').getContext('2d');
    Game.run(context);
};


